{{ config(materialized='table') }}


WITH job_base AS (
  SELECT DISTINCT -- duplicate the rows
    ID, TITLE, JOB_CATEGORY,
    JOB_DATE, CITY, STATE, EMPLOYMENT_TYPE,
    ORGANIZATION, ORGANIZATION_URL, URL,
    SOURCE_TYPE, SOURCE, SOURCE_DOMAIN,
    ORGANIZATION_LOGO, REMOTE_DERIVED, RECRUITER_NAME, RECRUITER_TITLE,
    RECRUITER_URL, LINKEDIN_ORG_URL,
    ORG_SIZE, LINKEDIN_ORG_INDUSTRY,
    LINKEDIN_ORG_HEADQUARTERS,
    LINKEDIN_ORG_TYPE, LINKEDIN_ORG_FOUNDEDDATE,
    LINKEDIN_ORG_SPECIALTIES, LINKEDIN_ORG_LOCATIONS,
    LINKEDIN_ORG_DESCRIPTION, LINKEDIN_ORG_RECRUITMENT_AGENCY_DERIVED,
    SENIORITY, DIRECTAPPLY,
    LINKEDIN_ORG_SLUG
  FROM {{ source('linkedin_raw', 'LINKEDIN_JOB_API_CLEANED_DATA') }}
),
city AS (
   SELECT
     DISTINCT CITY, CITY_STANDARDIZED, STATE -- duplicate the rows
   FROM {{ source('linkedin_int', 'CITY') }}
),
state AS (
   SELECT
    DISTINCT CITY_STANDARDIZED, STATE_STANDARDIZED -- duplicate the rows
   FROM {{ source('linkedin_int', 'STATE') }}
),
exp AS (
   SELECT
    DISTINCT SENIORITY, SENIORITY_STANDARDIZED -- duplicate the rows
   FROM {{ source('linkedin_int', 'JOB_SENIORITY') }}
)
SELECT
  jb.ID, jb.TITLE, jb.JOB_CATEGORY,
  jb.JOB_DATE, jb.EMPLOYMENT_TYPE,
  MAX(c.CITY_STANDARDIZED) AS CITY, -- duplicate the rows
  MAX(s.STATE_STANDARDIZED) AS STATE, -- duplicate the rows
  MAX(exp.SENIORITY_STANDARDIZED) AS SENIORITY, -- duplicate the rows
  jb.ORGANIZATION, jb.ORGANIZATION_URL, jb.URL,
  jb.SOURCE_TYPE, jb.SOURCE, jb.SOURCE_DOMAIN,
  jb.ORGANIZATION_LOGO, jb.REMOTE_DERIVED,
  jb.RECRUITER_NAME, jb.RECRUITER_TITLE,
  jb.RECRUITER_URL, jb.LINKEDIN_ORG_URL,
  jb.ORG_SIZE, jb.LINKEDIN_ORG_INDUSTRY,
  jb.LINKEDIN_ORG_HEADQUARTERS,
  jb.LINKEDIN_ORG_TYPE, jb.LINKEDIN_ORG_FOUNDEDDATE,
  jb.LINKEDIN_ORG_SPECIALTIES, jb.LINKEDIN_ORG_LOCATIONS,
  jb.LINKEDIN_ORG_DESCRIPTION, jb.LINKEDIN_ORG_RECRUITMENT_AGENCY_DERIVED,
  jb.DIRECTAPPLY, jb.LINKEDIN_ORG_SLUG
FROM job_base AS jb
JOIN city AS c ON jb.CITY = c.CITY
JOIN state AS s ON c.CITY_STANDARDIZED = s.CITY_STANDARDIZED
JOIN exp ON jb.SENIORITY = exp.SENIORITY
GROUP BY -- duplicate the rows
  jb.ID, jb.TITLE, jb.JOB_CATEGORY,
  jb.JOB_DATE, jb.EMPLOYMENT_TYPE,
  jb.ORGANIZATION, jb.ORGANIZATION_URL, jb.URL,
  jb.SOURCE_TYPE, jb.SOURCE, jb.SOURCE_DOMAIN,
  jb.ORGANIZATION_LOGO, jb.REMOTE_DERIVED,
  jb.RECRUITER_NAME, jb.RECRUITER_TITLE,
  jb.RECRUITER_URL, jb.LINKEDIN_ORG_URL,
  jb.ORG_SIZE, jb.LINKEDIN_ORG_INDUSTRY,
  jb.LINKEDIN_ORG_HEADQUARTERS,
  jb.LINKEDIN_ORG_TYPE, jb.LINKEDIN_ORG_FOUNDEDDATE,
  jb.LINKEDIN_ORG_SPECIALTIES, jb.LINKEDIN_ORG_LOCATIONS,
  jb.LINKEDIN_ORG_DESCRIPTION, jb.LINKEDIN_ORG_RECRUITMENT_AGENCY_DERIVED,
  jb.DIRECTAPPLY, jb.LINKEDIN_ORG_SLUG
